spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

    producer:
      key-serializer: ${SPRING_KAFKA_PRODUCER_KEY_SERIALIZER}
      value-serializer: ${SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER}

    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: ${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
      key-deserializer: ${SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER}
      value-deserializer: ${SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER}
      properties:
        spring.json.trusted.packages: com.quinzex.*

    listener:
      missing-topics-fatal: ${SPRING_KAFKA_LISTENER_MISSING_TOPICS_FATAL}
      concurrency: 1

  data:
    redis:
      url: ${SPRING_DATA_REDIS_HOST}

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com

admin:
  email: ${ADMIN_EMAIL}

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


jwt:
  rsa:
    public-key: ${JWT_RSA_PUBLIC_KEY}
    private-key: ${JWT_RSA_PRIVATE_KEY}
aws:
  region: ap-south-2
  s3:
    bucket: careervidya1

security:
  s3:
    secret: ${SECURITY_S3_SECRET}

